##
# Ansible playbook for sample data.
#

---
- hosts: all
  gather_facts: False

  tasks:
    - name: Upload sample course data
      action: copy src=mongo-reset-data.js dest=/tmp/mongo-reset-data.js

    - name: Insert sample Mongo course data
      action: command mongo trainingwheels /tmp/mongo-reset-data.js

    - name: Create instructor
      action: "command ./tw u:c 1 instructor chdir=/var/trainingwheels-source/controller/cli creates=/twhome/instructor"

    - name: Create bobby
      action: "command ./tw u:c 1 bobby chdir=/var/trainingwheels-source/controller/cli creates=/twhome/bobby"

    - name: Create sally
      action: "command ./tw u:c 1 sally chdir=/var/trainingwheels-source/controller/cli creates=/twhome/sally"

    - name: Create instructor resources
      action: "command ./tw r:c 1 instructor chdir=/var/trainingwheels-source/controller/cli creates=/twhome/instructor/mycourse"
